---
name: Build wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
          CIBW_ARCHS: auto64
          CIBW_TEST_REQUIRES: pytest syrupy
          CIBW_TEST_COMMAND: python -m pytest -vv {project}/tests

          # Don't build PyPy and MUSL wheels for now
          CIBW_SKIP: "pp* *-musllinux_*"

      - uses: actions/upload-artifact@v4
        with:
          name: piper-${{ matrix.os }}
          path: ./wheelhouse/*.whl
